[[Clause_Substantive]]
== Description of Substantive Changes

=== New Optional Class Defined in Clause 7.4 Bounding Volume Hierarchy
This is a new optional class that describes the I3S bounding volume hierarchy. This class references two other classes. See obb below.

=== Correction Warning – Reference Clause 7.5.5 LoD Selection Metrics
In version 1.0, the property maxError was considered as a mandatory element in all of the examples and in the text. However, in the class property table this property was not highlighted as mandatory. This was an error in the version 1.0 document. This is corrected in version 1.1.

=== New Optional Class Defined in Clause 7.6.5.6 obb
This is an optional class that defines the properties for an oriented bounding box. ‘obb’ was in version 1.0 but its properties were not clearly defined in one location in the document. The new class provides a single table with all properties defined in one location.

=== New Optional Property Defined in Clause 7.6.4.5 Field property Domain
A new property domain has been added to the class Field. Attribute domains are rules that describe the legal values of a field type, providing a method for enforcing data integrity. Attribute domains are used to constrain the values allowed in a particular attribute. They can be thought of as filters. The addition of domain property requires the addition of two new classes to the I3S Community Standard: domain and domainCodedValues. These are new clauses 7.6.5.4.1 and 7.6.5.4.2.




