[[Clause_Substantive]]
== Description of Substantive Changes

=== Point Cloud Scene Layers
The ability to code, stream, and store point cloud scene layers is a key update and extension of the I3S Community Standard. The addition of point cloud scene layers resulted in the addition of a number of new classes and profiles and profiles with extensions of the existing classes as defined in version 1.0 of the I3S Community Standard. 

The addition of the Point Cloud Scene Layer capability to I3S resulted in a number of additions to the Community Standard

- New optional properties added to Class 3dSceneLayerInfo (see below)
- New optional properties added to Class LoD Selection Metrics (see below)
- The addition of a new optional class elevationInfo (see below)
- A new major section: 9.4	Point Cloud Scene Layer that provids informative background and a structure example.
- The addition of a new Annex: Annex I I3S Point Cloud Scene Layer Profile. This Annex provides the majority of the information on how to implement a I3S Point Cloud Scene Layer. This Annex defines profiles of a number of the core I3S classes: 3dSceneLayerInfo, attributeInfo, Store, Index, defaultGeometrySchema, vertexAttributes. 
- A new Class _Node_ specifically for Point Cloud Scene Layers.
- A new Class _Stats_ specifically for Point Cloud Scene Layers. This class contains statistics about each attribute. Statistics are useful to estimate attribute distribution and range.
- A new Class _Labels_ specifically for Point Cloud Scene Layers. The statistics document may contain labeling information for the attribute values.


=== Clause 7.4 Bounding Volume Hierarchy - New Optional Class Defined 
This is a new optional class that describes the I3S bounding volume hierarchy. This class references two other classes. See obb below.

===  Clause 7.5.5 LoD Selection Metrics - Correction Warning
In version 1.0, the property maxError was considered as a mandatory element in all of the examples and in the text. However, in the class property table this property was not highlighted as mandatory. This was an error in the version 1.0 document. This is corrected in version 1.1.

=== Clause 7.6.4.1 Class 3dSceneLayerInfo
. spatialReference now has its own clause with greater detail. There is a cross reference from the table to the new clause.
. heightModelInfo now has its own clause with greater detail. There is a cross reference from the table to the new clause. This includes an enumeration of the allowed height units.
.	New optional properties added to this class. These properties were added based on implementation experience or in support of the new Point Cloud capability.
..	ZFactor: Define conversion factor for elevation unit. This was added in support of point cloud scene layers.
..	elevationInfo - An object containing elevation drawing information. If absent, any content of the scene layer is drawn at its z coordinate. This was added in support of point cloud scene layers.
..	popupinfo: PopupInfo of the scene layer.
..	disablePopup: Indicates if client application will show the popup information.
..	statisticsInfo: Contains the statistical information for a layer.

These are all new optional elements either added in support of Point Cloud or requested by the implementation community. They do not affect backwards compatability.

=== Clause 7.6.4.5 Field property Domain - New Optional Property Defined 
A new property domain has been added to the class Field. Attribute domains are rules that describe the legal values of a field type, providing a method for enforcing data integrity. Attribute domains are used to constrain the values allowed in a particular attribute. They can be thought of as filters. The addition of domain property requires the addition of two new classes to the I3S Community Standard: domain and domainCodedValues. These are new clauses 7.6.5.4.1 and 7.6.5.4.2.

=== 7.6.4.11 elevationInfo - New Class
This is a new class added in support of point cloud scene layers. _elevationInfo_ defines how content in a scene layer is aligned to the ground.

=== Clause 7.6.4.13 ServiceUpdateTimeStamp - New class
ServiceUpdateTimeStamp is a new optional class in this revision. This object provides a time stamp about when the I3S service or the source of the service was created or updated.
 
===  Clause 7.6.5.6 obb - New Optional Class Defined
This is an optional class that defines the properties for an oriented bounding box. ‘obb’ was in version 1.0 but its properties were not clearly defined in one location in the document. The new class provides a single table with all properties defined in one location.

=== Clause 9.5 SLPK Hash Table - New Clause: 
Scanning an SLPK (ZIP store) containing millions of documents is usually inefficient and slow. To improve first load and file scanning performances, a hash table file may be added to the SLPK.




