[[Clause_Substantive]]
== Description of Substantive Changes

=== Clause 7.4 Bounding Volume Hierarchy - New Optional Class Defined 
This is a new optional class that describes the I3S bounding volume hierarchy. This class references two other classes. See obb below.

===  Clause 7.5.5 LoD Selection Metrics - Correction Warning
In version 1.0, the property maxError was considered as a mandatory element in all of the examples and in the text. However, in the class property table this property was not highlighted as mandatory. This was an error in the version 1.0 document. This is corrected in version 1.1.

=== Clause 7.6.4.1 Class 3dSceneLayerInfo
. spatialReference now has its own clause with greater detail. There is a cross reference from the table to the new clause.
. heightModelInfo now has its own clause with greater detail. There is a cross reference from the table to the new clause. This includes an enumeration of the allowed height units.
.	New optional properties added to this class. These properties were added based on implementation experience or in support of the new Point Cloud capability.
..	ZFactor: Define conversion factor for elevation unit. This was added in support of point cloud scene layers.
..	elevationInfo - An object containing elevation drawing information. If absent, any content of the scene layer is drawn at its z coordinate. This was added in support of point cloud scene layers.
..	popupinfo: PopupInfo of the scene layer.
..	disablePopup: Indicates if client application will show the popup information.
..	statisticsInfo: Contains the statistical information for a layer.

These are all new optional elements either added in support of Point Cloud or requested by the implementation community. They do not affect backwards compatability.
 
===  Clause 7.6.5.6 obb - New Optional Class Defined
This is an optional class that defines the properties for an oriented bounding box. ‘obb’ was in version 1.0 but its properties were not clearly defined in one location in the document. The new class provides a single table with all properties defined in one location.

=== New Optional Property Defined in Clause 7.6.4.5 Field property Domain
A new property domain has been added to the class Field. Attribute domains are rules that describe the legal values of a field type, providing a method for enforcing data integrity. Attribute domains are used to constrain the values allowed in a particular attribute. They can be thought of as filters. The addition of domain property requires the addition of two new classes to the I3S Community Standard: domain and domainCodedValues. These are new clauses 7.6.5.4.1 and 7.6.5.4.2.




