== Introduction

A single I3S data set, referred to as a Scene Layer, is a container for arbitrarily large amounts of heterogeneously distributed 3D geographic data. Scene Layers are designed to be used in mobile, desktop, and server-based workflows and can be accessed over the web or as local files.

These release notes describe in detail the changes and enhancements to the original OGC I3S Community Standard. This is a 1.1 revision. This I3S revision including al the changes and enhancements are backwards compatible with the version 1.0 (17-14r5)

===	Scope

The completed Work Item changes to the OGC I3S Community Standard include:

-	Point Cloud Scene Layer type.
-	For existing layer types, the addition of:
--	Oriented Bounding Boxes
--	Attribute Domain Rules
--	Service Update Timestamp
--	Index hash table for improved performance.
-	Numerous editorial updates/corrections to improve readability.

In relation to the last work item, the following changes were applied to all tables in the I3S Community Standard:

. For all the class tables, in the previous version mandatory properties were identified with an “*”. In version 1.1, mandatory properties are highlighted using a bold type font.
. In all property tables, the type designation “Float” is changed to “Number”.
. In all property tables, the type designation “Integer” is changed to “Number”.
. In all property tables, the type designation “Date” is changed to “String”
. Added examples to most classes.

None of these global changes affect backwards compatibilty.

===	Document contributor contact points

All questions regarding this document should be directed to the contacts provided below or the referenced standard editor(s).

.Contacts
[width="80%",options="header"]
|====================
|Name |Organization
|Carl Reed | Carl Reed & Associates
|====================
